name: "Análisis SAST con CodeQL"

on:
  push:
    branches:
      - PruebaReporte

jobs:
  analyze:
    name: Analizar Código
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Inicializar CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: 'csharp'

      # - name: Restaurar dependencias
      #   run : dotnet restore

      #- name: Compilar proyecto (build explícito)
      #  run: dotnet build --configuration Release
      - name: Autobuild de C#
        uses: github/codeql-action/autobuild@v4

      - name: Ejecutar Análisis
        uses: github/codeql-action/analyze@v4
